### ISSUE TITLE
Final Pre-Release Functionality Testing 📋

### ISSUE THREAD

**Issue by matt-auckland** [Encrypt-S/openalias-website#18]
Functionality to be tested before pushing live:
- [x] Can register an address 
- [x] Can update an address 
- [x] Can't update a non-registered address 
- [x] Doesn't allow a bad signature 
- [x] Doesn't allow a bad address 
- [x] Doesn't allow a bad alias name 
- [x] Handles network request errors appropriately 
- [x] Update alias 'next' button needs to be changed
- [x] Step 1/2/3 on updating need to be fixed
- [x] Step 1/2 on confirming (when updating need to change)
- [x] Handle error message from server
- [x] Previous address verifications wasnt sent when updating
- [x] FAQs are back-the-front
- [x] Adds cursor hover to selector on 'create alais'
- [x] Entering previous addresss details is reserved when updating

We also need to make sure the copy is good for everything, some parts of the website are a bit awkwardly phrased

**Comment by ro-savage** [comment]
Closed by PR #23
